# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rservice.proto\x12\x0corchestrator"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t"2\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03"F\n\x11\x43ompletionRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05"L\n\x12\x43ompletionResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t\x12\x13\n\x0btokens_used\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\t"w\n\x13OptimizationRequest\x12\x14\n\x0cproblem_type\x18\x01 \x01(\t\x12\x18\n\x10\x63onstraints_json\x18\x02 \x01(\t\x12\x17\n\x0fobjectives_json\x18\x03 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x05"b\n\x14OptimizationResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t""\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t"\x89\x01\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12\x14\n\x0c\x63ompleted_at\x18\x06 \x01(\x03\x32\xcb\x02\n\tAIService\x12=\n\x04Ping\x12\x19.orchestrator.PingRequest\x1a\x1a.orchestrator.PingResponse\x12R\n\rGetCompletion\x12\x1f.orchestrator.CompletionRequest\x1a .orchestrator.CompletionResponse\x12Z\n\x11SolveOptimization\x12!.orchestrator.OptimizationRequest\x1a".orchestrator.OptimizationResponse\x12O\n\x0cGetJobStatus\x12\x1e.orchestrator.JobStatusRequest\x1a\x1f.orchestrator.JobStatusResponseB?Z=https://github.com/Tshogun/Scheduling_Agent_Prod/shared/protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z=https://github.com/Tshogun/Scheduling_Agent_Prod/shared/proto"
    )
    _globals["_PINGREQUEST"]._serialized_start = 31
    _globals["_PINGREQUEST"]._serialized_end = 61
    _globals["_PINGRESPONSE"]._serialized_start = 63
    _globals["_PINGRESPONSE"]._serialized_end = 113
    _globals["_COMPLETIONREQUEST"]._serialized_start = 115
    _globals["_COMPLETIONREQUEST"]._serialized_end = 185
    _globals["_COMPLETIONRESPONSE"]._serialized_start = 187
    _globals["_COMPLETIONRESPONSE"]._serialized_end = 263
    _globals["_OPTIMIZATIONREQUEST"]._serialized_start = 265
    _globals["_OPTIMIZATIONREQUEST"]._serialized_end = 384
    _globals["_OPTIMIZATIONRESPONSE"]._serialized_start = 386
    _globals["_OPTIMIZATIONRESPONSE"]._serialized_end = 484
    _globals["_JOBSTATUSREQUEST"]._serialized_start = 486
    _globals["_JOBSTATUSREQUEST"]._serialized_end = 520
    _globals["_JOBSTATUSRESPONSE"]._serialized_start = 523
    _globals["_JOBSTATUSRESPONSE"]._serialized_end = 660
    _globals["_AISERVICE"]._serialized_start = 663
    _globals["_AISERVICE"]._serialized_end = 994

# @@protoc_insertion_point(module_scope)
