# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """AI Service for LLM and OR-Tools operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/orchestrator.AIService/Ping',
                request_serializer=service__pb2.PingRequest.SerializeToString,
                response_deserializer=service__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetCompletion = channel.unary_unary(
                '/orchestrator.AIService/GetCompletion',
                request_serializer=service__pb2.CompletionRequest.SerializeToString,
                response_deserializer=service__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.SolveOptimization = channel.unary_unary(
                '/orchestrator.AIService/SolveOptimization',
                request_serializer=service__pb2.OptimizationRequest.SerializeToString,
                response_deserializer=service__pb2.OptimizationResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/orchestrator.AIService/GetJobStatus',
                request_serializer=service__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=service__pb2.JobStatusResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """AI Service for LLM and OR-Tools operations
    """

    def Ping(self, request, context):
        """Simple ping for health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompletion(self, request, context):
        """LLM completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolveOptimization(self, request, context):
        """OR-Tools solver (async via RabbitMQ recommended)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get solver job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=service__pb2.PingRequest.FromString,
                    response_serializer=service__pb2.PingResponse.SerializeToString,
            ),
            'GetCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompletion,
                    request_deserializer=service__pb2.CompletionRequest.FromString,
                    response_serializer=service__pb2.CompletionResponse.SerializeToString,
            ),
            'SolveOptimization': grpc.unary_unary_rpc_method_handler(
                    servicer.SolveOptimization,
                    request_deserializer=service__pb2.OptimizationRequest.FromString,
                    response_serializer=service__pb2.OptimizationResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=service__pb2.JobStatusRequest.FromString,
                    response_serializer=service__pb2.JobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """AI Service for LLM and OR-Tools operations
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AIService/Ping',
            service__pb2.PingRequest.SerializeToString,
            service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AIService/GetCompletion',
            service__pb2.CompletionRequest.SerializeToString,
            service__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolveOptimization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AIService/SolveOptimization',
            service__pb2.OptimizationRequest.SerializeToString,
            service__pb2.OptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AIService/GetJobStatus',
            service__pb2.JobStatusRequest.SerializeToString,
            service__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
