name: GolangCI-Lint (go-service)

on:
  push:
    branches: ["**"]
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-go-service:
    name: Lint Go Service
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          working-directory: backend/servies/go-orchestrator