name: Python Lint & Format

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    name: Run Ruff and Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run Ruff (linter)
        run: |
          ruff check backend/services/python-services

      - name: Run Black (check formatting only)
        run: |
          black --check backend/services/python-services
