# Root .golangci.yml for Go service
run:
  timeout: 5m
  tests: false

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/your-org/your-project
  govet:
    enable-all: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
